name: "CI"

on:
  pull_request:
  push:
    branches:
      - '**'
  # workflow is reused by cd.yml
  workflow_call:
    
jobs:

  Testing:
    strategy:
      matrix:
        php-version: ['8.2', '8.3', '8.4']
        # Ubuntu Noble is not available for now, because of a curl arm64 bug:
        # https://bugs.launchpad.net/ubuntu/+source/curl/+bug/2073448
        os-variant: ['jammy', 'bookworm', 'alpine']
        # temporarily disabled 8.4@alpine (lack of such image)
        exclude:
          - php-version: '8.4'
            os-variant: 'alpine'
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build test runner
      uses: docker/build-push-action@v5
      with:
        push: false
        target: test-runner
        tags: php${{ matrix.php-version }}-${{ matrix.os-variant}}-checks
        build-args: |
          PHP_VERSION=${{ matrix.php-version }}
          OS_VARIANT=${{ matrix.os-variant }}
    - name: Run tests
      run: docker  run --rm -v ./:/var/www/html php${{ matrix.php-version }}-${{ matrix.os-variant}}-checks sh -c "composer install && composer test:all"
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Test building dist image
      uses: docker/build-push-action@v5
      with:
        push: false
        target: dist
        build-args: |
          PHP_VERSION=${{ matrix.php-version }}
          OS_VARIANT=${{ matrix.os-variant }}
